<?php

return [
    'active' => 'modern-neutral',

    'themes' => [
        'modern-neutral' => [
            'name' => 'Modern Neutral',
            'background' => '#FAFAF9',
            'surface' => '#FFFFFF',
            'surface_muted' => '#F5F5F4',
            'text_primary' => '#171717',
            'text_secondary' => '#737373',
            'text_muted' => '#A3A3A3',
            'border' => '#E7E5E4',
            'primary' => '#171717',
            'primary_hover' => '#0A0A0A',
            'primary_text' => '#FFFFFF',
            'accent' => '#B4232D',
            'accent_hover' => '#941B24',
            'accent_soft' => '#FFF1F2',
            'display_font' => "'Bodoni Moda', serif",
            'body_font' => "'Plus Jakarta Sans', sans-serif",
            'container_width' => '1320px',
        ],
        'noir' => [
            'name' => 'Noir',
            'background' => '#111111',
            'surface' => '#191919',
            'surface_muted' => '#242424',
            'text_primary' => '#F5F5F4',
            'text_secondary' => '#A8A29E',
            'text_muted' => '#78716C',
            'border' => '#343434',
            'primary' => '#F5F5F4',
            'primary_hover' => '#FFFFFF',
            'primary_text' => '#111111',
            'accent' => '#D8B86A',
            'accent_hover' => '#F0D58F',
            'accent_soft' => '#2B271D',
            'display_font' => "'Bodoni Moda', serif",
            'body_font' => "'Plus Jakarta Sans', sans-serif",
            'container_width' => '1320px',
        ],
    ],
];
