<?php

return [
    // Change this value to: atelier, noir, street, modern-neutral, or trizync.
    'active' => 'modern-neutral',

    'themes' => [
        'atelier' => [
            'name' => 'Atelier',
            'background' => '#f5f3ee',
            'surface' => '#ffffff',
            'surface_alt' => '#ebe7df',
            'text' => '#171714',
            'muted' => '#6f6c64',
            'accent' => '#9f3025',
            'accent_hover' => '#742018',
            'border' => '#d8d3c9',
            'display_font' => 'Bodoni Moda',
            'body_font' => 'Plus Jakarta Sans',
            'container_width' => '1440px',
            'section_spacing' => '84px',
            'image_radius' => '0px',
            'card_radius' => '0px',
            'eyebrow' => 'THE EDIT',
            'hero_action' => 'Explore Collection',
            'view_all' => 'Discover All',
            'category_kicker' => 'SHOP BY MOOD',
            'products_kicker' => 'CURATED FOR YOU',
        ],
        'noir' => [
            'name' => 'Noir',
            'background' => '#111111',
            'surface' => '#191919',
            'surface_alt' => '#242424',
            'text' => '#f4f1e9',
            'muted' => '#aaa69d',
            'accent' => '#d8b86a',
            'accent_hover' => '#f0d58f',
            'border' => '#383838',
        ],
        'street' => [
            'name' => 'Street',
            'background' => '#f0f0ec',
            'surface' => '#ffffff',
            'surface_alt' => '#dfe946',
            'text' => '#101010',
            'muted' => '#565656',
            'accent' => '#ed3d24',
            'accent_hover' => '#b82615',
            'border' => '#171717',
            'display_font' => 'Plus Jakarta Sans',
            'image_radius' => '0px',
            'card_radius' => '0px',
            'eyebrow' => 'NEW DROP',
            'category_kicker' => 'FIND YOUR FIT',
        ],
        'modern-neutral' => [
            'name' => 'Modern Neutral',
            'background' => '#FAFAF9',
            'surface' => '#FFFFFF',
            'surface_alt' => '#F5F5F4',
            'surface_muted' => '#F5F5F4',
            'text' => '#171717',
            'text_secondary' => '#737373',
            'text_muted' => '#A3A3A3',
            'muted' => '#737373',
            'border' => '#E7E5E4',
            'primary' => '#171717',
            'primary_hover' => '#0A0A0A',
            'primary_text' => '#FFFFFF',
            'accent' => '#B4232D',
            'accent_hover' => '#941B24',
            'accent_soft' => '#FFF1F2',
            'display_font' => 'Bodoni Moda',
            'body_font' => 'Plus Jakarta Sans',
            'container_width' => '1440px',
            'section_spacing' => '84px',
            'image_radius' => '0px',
            'card_radius' => '0px',
            'eyebrow' => 'MODERN CLASSICS',
            'hero_action' => 'Shop the Collection',
            'view_all' => 'View All Pieces',
            'category_kicker' => 'SHOP BY CATEGORY',
            'products_kicker' => 'THE LATEST EDIT',
        ],
        'trizync' => [
            'name' => 'TriZync',
            'background' => '#FAFAFA',
            'surface' => '#FFFFFF',
            'surface_alt' => '#F6F4F8',
            'surface_muted' => '#F6F4F8',
            'text' => '#171717',
            'text_secondary' => '#66616A',
            'text_muted' => '#969198',
            'muted' => '#66616A',
            'border' => '#E7E2EA',
            'primary' => '#411264',
            'primary_hover' => '#34104F',
            'primary_text' => '#FFFFFF',
            'accent' => '#F0A60A',
            'accent_hover' => '#D99408',
            'accent_soft' => '#FFF7E5',
        ],
    ],
];
